#!/usr/bin/env python3
"""C++ headers of the Spume layer, generated from the campaign's model of the reference's Foam mode.

    python emit_spume_header.py            write both headers
    python emit_spume_header.py --check    exit 1 when a header on disk is not what the model gives
    python emit_spume_header.py --engine [tool]
                                           the engine's renderer (AmanitaOceanFathomRender, default the one in
                                           build-spume-dsp) against the model on the whole renders the golden vectors
                                           are cut from: with the layer, the base alone, the layer alone

    Source/dsp/SpumeConstants.h      every constant of the layer: those of the model (foam/model/foam_structure.py with
                                     structure_final.json, and foam_model.py; foam/findings/FOAM_STATE.md gives their
                                     meaning and status) and Ocean's own, which are set in this file
    Tests/SpumeGoldenVectors.h       the diffuser's impulse response, and renders of the model: a fresh instance,
                                     short stimuli, excerpts of the model's output where the layer is strongest

The model is the campaign's own, in foam/model/, and is imported, not repeated here. foam_model.render is written for
48 kHz; `render` below puts the same parts together at any host rate (the input converter, foam_model.foam_input,
the base with its oscillator origin, the output converter) and is checked against foam_model.render at 48 kHz, where
the two must be the same numbers. What the base compiles and caches at run time goes under Analyzer/Results
(abyss/model/base.py).

One vector moves Macro. The model moves its two gains once per block of 44 internal samples, and which block is the
first to use a value the host set with a call at frame h is the reference's handling of host blocks
(foam_model.first_block). The vector therefore names that block for every change, and the test hands the engine the
value in front of it.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MODEL = HERE / "foam" / "model"
for path in (HERE, MODEL):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import converters  # noqa: E402
import foam_model  # noqa: E402
import foam_structure  # noqa: E402
import fcommon  # noqa: E402
from emit_undertow_header import bits, noise, real, rows, signal, single, stimulus  # noqa: E402,F401

B, nm = fcommon.B, fcommon.nm
CONSTANTS_HEADER = ROOT / "Source/dsp/SpumeConstants.h"
GOLDEN_HEADER = ROOT / "Tests/SpumeGoldenVectors.h"
GENERATOR = "Analyzer/Campaigns/RevOceanCharacterization/emit_spume_header.py"
SOURCES = [MODEL / "foam_structure.py", MODEL / "structure_final.json", MODEL / "foam_model.py", MODEL / "fcommon.py",
           HERE / "abyss" / "model" / "base.py", HERE / "abyss" / "model" / "abyss_core.c"]
F = np.float32

# ---------------------------------------------------------------- Ocean's own constants (not measured)

OCEAN = {
    "gainFloor": 1.0e-12,              # a gain this near its target has arrived
}


def head(title: list) -> str:
    lines = [f"// Generated by {GENERATOR}.", "// Do not edit: change the model or the generator and run it again.", "//"]
    lines += [f"// {line}" for line in title]
    lines += ["//", "// Made from (SHA-256):"]
    lines += [f"//   {path.relative_to(ROOT)}  {hashlib.sha256(path.read_bytes()).hexdigest()}" for path in SOURCES]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- the constants

def constants_header() -> str:
    structure = foam_model.structure()
    delays, gains = structure["delays"], structure["gains"]
    assert len(delays) == 7 and all(len(stage) == 4 for stage in delays) and len(gains) == 7
    assert all(np.ndim(gain) == 0 for gain in gains)
    assert np.array_equal(foam_structure.H4, [[1, 1, 1, 1], [1, -1, 1, -1], [1, 1, -1, -1], [1, -1, -1, 1]])
    assert foam_model.BLOCK == 44 and foam_model.BLOCK_PHASE == 43
    assert foam_model.SMOOTH == float(np.exp(-44.0 / 441.0))
    # the input to each of the four paths and the factor of a mix, as foam_structure.diffuse has them
    probe = foam_structure.diffuse(np.array([1.0, 0.0]), {"delays": [[1, 1, 1, 1]], "gains": [0.0]})
    assert probe[1] == 4 * 0.5
    flat = [delay for stage in delays for delay in stage]
    table = ",\n".join("    { " + ", ".join(str(delay) for delay in stage) + " }" for stage in delays)
    body = f"""#pragma once

#include <array>

namespace amanita::dsp::spume
{{
// The diffuser (FOAM_STATE.md, section 2): seven stages of four parallel
// Schroeder all-passes, y[n] = g x[n] + x[n - D] - g y[n - D], with one gain
// per stage. The input goes to each of the four paths times `pathInputGain`;
// between two stages the four are mixed by the Sylvester Hadamard matrix of
// order 4 times `mixGain`; the output is their plain sum. Delays in internal
// samples, by stage and path; path 0 takes the sum row of the mix.
inline constexpr int stageCount = {len(delays)};
inline constexpr int pathCount = 4;
inline constexpr std::array<std::array<int, pathCount>, stageCount> delaySamples {{{{
{table}
}}}};
inline constexpr std::array<double, stageCount> stageGain {{
    {", ".join(real(gain) for gain in gains)}
}};
inline constexpr double pathInputGain = 0.5;
inline constexpr double mixGain = 0.5;
inline constexpr int longestDelaySamples = {max(flat)};
inline constexpr int totalDelaySamples = {sum(flat)};

// Macro (FOAM_STATE.md, section 3): the plain input times cos(pi/2 Macro) and
// the diffused one times sin(pi/2 Macro). Each of the two gains moves once per
// block of `gainBlockSamples` internal samples and is held over it: of what
// separates it from its target, `gainBlockRetention` stays, which is
// exp(-44/441), a one-pole of 10 ms run at the block rate. A block begins at
// the internal samples `gainBlockPhase` modulo `gainBlockSamples`.
inline constexpr int gainBlockSamples = {foam_model.BLOCK};
inline constexpr int gainBlockPhase = {foam_model.BLOCK_PHASE};
inline constexpr double gainBlockRetention = {real(foam_model.SMOOTH)};

// Ocean's own (nothing of this was measured).
// A gain this near its target has arrived.
inline constexpr double gainFloor = {real(OCEAN["gainFloor"])};
}} // namespace amanita::dsp::spume
"""
    title = ["Constants of the Spume layer: the campaign's model of the reference's Foam mode",
             "(Analyzer/Campaigns/RevOceanCharacterization/foam/findings/FOAM_STATE.md gives their meaning",
             "and status) and Ocean's own."]
    return head(title) + body


# ---------------------------------------------------------------- the model at any host rate

DECAY_SECONDS, SIZE_PERCENT = 2.0, 100.0
_KNOBS = nm.constants()["parameters"]
ENGINE_DECAY_SECONDS = F(nm.host_value(_KNOBS["decay"], DECAY_SECONDS))
ENGINE_SIZE_SCALE = F(nm.host_value(_KNOBS["size"], SIZE_PERCENT) / 100.0)


def render(x: np.ndarray, rate: int, first_frame: int, macro, origin: int) -> tuple:
    """(raw output frames [first_frame, first_frame + len(x)), index of the first internal sample) of the model.
    macro: a number, or [initial, (first block, value), ...] with the internal sample at which the first block of 44
    that uses each value begins."""
    x = np.asarray(x, dtype=np.float64)
    first, u = B.to_internal(x, rate, first_frame)
    if isinstance(macro, list):
        index = first + np.arange(len(u))
        cosine = np.full(len(u), np.cos(0.5 * np.pi * macro[0]))
        sine = np.full(len(u), np.sin(0.5 * np.pi * macro[0]))
        for block, value in macro[1:]:
            # foam_model.macro_gains with the first block given instead of the host frame it follows from
            assert block % foam_model.BLOCK == foam_model.BLOCK_PHASE and block > index[0]
            at = int(block - index[0])
            blocks = (index[at:] - block) // foam_model.BLOCK + 1
            for gains, target in ((cosine, np.cos(0.5 * np.pi * value)), (sine, np.sin(0.5 * np.pi * value))):
                gains[at:] = target + (gains[at - 1] - target) * foam_model.SMOOTH ** blocks
        macro = (cosine, sine)
    driven = nm.equalise(fcommon.DATA, foam_model.foam_input(u, macro))
    taps = B.core(driven, first + fcommon.DELAY, origin, fcommon.values_for(DECAY_SECONDS, SIZE_PERCENT))
    return B.to_host(taps, first, rate, first_frame, first_frame + len(x), fcommon.DATA), first


# ---------------------------------------------------------------- the golden vectors

EXCERPT_FRAMES = 160
EXCERPTS = 3                  # per vector: where the layer is strongest, each a good way from the others
EXCERPT_SPACING_SECONDS = 0.3
EXCERPT_LAYER_SHARE_DB = -25.0
KERNEL_SAMPLES = 12000        # of the diffuser's impulse response, sample by sample: 806 of them are not zero
KERNEL_SEGMENT = 4000         # ... and its sum and energy up to every multiple of this, as far as
KERNEL_REACH = 60000          # this: 1.36 s, where the answer is at its height

# name, stimulus, host rate, Macro, seconds, first frame of the instance's count, oscillator origin
VECTORS = (
    ("impulses48000", "impulses", 48000, 1.0, 2.7, 0, 0),
    ("burst48000", "burst", 48000, 0.5, 2.7, 0, 0),
    ("tone48000", "tone", 48000, 0.25, 2.7, 0, 0),
    ("late48000", "burst", 48000, 1.0, 2.7, 28800000, 23964028),
    ("impulses44100", "impulses", 44100, 0.5, 2.7, 0, 0),
    ("burst44100", "burst", 44100, 1.0, 2.7, 0, 0),
    ("tone44100", "tone", 44100, 0.25, 2.7, 0, 0),
)
# Macro in motion at 48 kHz: noise that runs on, Macro set with host calls that begin at these frames.
# The last comes 16 ms behind the one before it, which has not settled by then.
MOTION = ("motion48000", 48000, 2.4, 0.2, ((24000, 0.9), (43008, 0.4), (60416, 0.0), (86047, 1.0), (86815, 0.65)))
MOTION_AMPLITUDE, MOTION_CHANNEL = 0.2, 60
MOTION_EXCERPTS = (0, 2, 4)   # an excerpt behind each of these changes, where the output tells its first block from the next


def hashed_noise(count: int, channel: int) -> np.ndarray:
    """A single-precision number in [-1, 1) for every index, from a hash of it: the noise of Tests/DspTests.cpp
    (fathomNoise), which the tests can make again to the bit."""
    state = (np.arange(count, dtype=np.uint64) * np.uint64(2654435761) + np.uint64(channel * 40503 + 0x0EBB5EED)) & np.uint64(0xFFFFFFFF)
    state ^= state >> np.uint64(15)
    state = (state * np.uint64(2246822519)) & np.uint64(0xFFFFFFFF)
    state ^= state >> np.uint64(13)
    signed = state.astype(np.int64)
    signed[signed >= 1 << 31] -= 1 << 32
    return signed.astype(np.float32) / np.float32(2147483648.0)


def kernel_weights(count: int) -> np.ndarray:
    """A weight for every sample of the kernel (channel 0 of that noise): a sum of the kernel under these weights
    changes when any of its samples moves."""
    return hashed_noise(count, 0).astype(np.float64)


def running_noise(frames: int) -> np.ndarray:
    """The stimulus of the vector that moves Macro: that noise at `MOTION_AMPLITUDE`, channels `MOTION_CHANNEL` and the
    next for left and right. The header does not hold it; the test makes it."""
    return np.stack([F(MOTION_AMPLITUDE) * hashed_noise(frames, MOTION_CHANNEL + side) for side in (0, 1)], axis=1).astype(np.float32)


def excerpts_of(name: str, rate: int, model: np.ndarray, plain: np.ndarray) -> list:
    """Where the layer is strongest: `plain` is the model's output without what the layer adds (the base at the plain
    input's gain), so the difference is the diffused part alone."""
    layer = np.sum((model - plain) ** 2, axis=1)
    energy = np.convolve(layer, np.ones(EXCERPT_FRAMES), mode="valid")
    spacing = int(EXCERPT_SPACING_SECONDS * rate)
    starts = []
    for _ in range(EXCERPTS):
        start = int(np.argmax(energy))
        starts.append(start)
        energy[max(0, start - spacing):start + spacing] = -1.0
    out = []
    for start in sorted(starts):
        piece = model[start:start + EXCERPT_FRAMES]
        share = 10 * np.log10(np.sum((piece - plain[start:start + EXCERPT_FRAMES]) ** 2) / np.sum(piece ** 2))
        assert share > EXCERPT_LAYER_SHARE_DB, f"{name}: the layer is {share:.1f} dB of the excerpt at frame {start}"
        out.append((start, piece.astype(np.float32)))
        if "--verbose" in sys.argv:
            print(f"{name:16} excerpt at {start / rate:6.3f} s: layer {share:6.1f} dB of it, level {10 * np.log10(np.mean(piece ** 2)):7.1f} dBFS")
    return out


def golden_cases() -> list:
    """Every vector with its stimulus and the model's whole render: the golden header and --engine read this."""
    out = []
    for name, kind, rate, macro, seconds, first_frame, origin in VECTORS:
        latency = converters.reported_latency(rate)
        frames = int(seconds * rate)
        impulses, first, programme = stimulus(kind, rate, frames)
        x = signal(impulses, first, programme, frames + latency)
        model, first_sample = render(x, rate, first_frame, float(F(macro)), origin)
        plain, _ = render(x, rate, first_frame, 0.0, origin)
        if name == "impulses48000":            # the parts put together here are foam_model.render at 48 kHz
            assert np.array_equal(model, foam_model.render(x, first_frame, DECAY_SECONDS, SIZE_PERCENT, float(F(macro)), osc_origin=origin))
        out.append({"name": name, "rate": rate, "macro": F(macro), "firstFrame": first_frame, "origin": origin,
                    "impulses": impulses, "programmeFirst": first, "programme": programme, "changes": [], "noiseFrames": 0,
                    "x": x, "frames": frames, "model": model[latency:], "plain": plain[latency:],
                    "dry": float(np.cos(0.5 * np.pi * float(F(macro)))) * plain[latency:]})
    name, rate, seconds, initial, moves = MOTION
    latency = converters.reported_latency(rate)
    frames = int(seconds * rate)
    x = np.concatenate([running_noise(frames), np.zeros((latency, 2), np.float32)])
    changes = [(foam_model.first_block(frame), float(F(value))) for frame, value in moves]
    model, first_sample = render(x, rate, 0, [float(F(initial))] + changes, 0)
    # the same through the model's own path, which goes from the host frames to the blocks itself
    assert np.array_equal(model, foam_model.render(x, 0, DECAY_SECONDS, SIZE_PERCENT,
                                                    [float(F(initial))] + [(frame, float(F(value))) for frame, value in moves], osc_origin=0))
    plain, _ = render(x, rate, 0, 0.0, 0)
    # Where a change shows: where the output differs most from the one whose change comes a block later.
    starts = []
    for number in MOTION_EXCERPTS:
        later = [(block + foam_model.BLOCK if index == number else block, value) for index, (block, value) in enumerate(changes)]
        other, _ = render(x, rate, 0, [float(F(initial))] + later, 0)
        energy = np.convolve(np.sum((model - other)[latency:] ** 2, axis=1), np.ones(EXCERPT_FRAMES), mode="valid")
        starts.append(int(np.argmax(energy)))
        assert energy[starts[-1]] > 1e-12 and (number == MOTION_EXCERPTS[0] or starts[-1] > starts[-2] + EXCERPT_FRAMES)
    out.append({"name": name, "rate": rate, "macro": F(initial), "firstFrame": 0, "origin": 0, "impulses": [],
                "programmeFirst": 0, "programme": np.zeros((0, 2), np.float32), "changes": changes, "noiseFrames": frames,
                "x": x, "frames": frames, "model": model[latency:], "plain": plain[latency:], "dry": plain[latency:],
                "excerptStarts": starts})
    return out


def golden_header() -> str:
    structure = foam_model.structure()
    kernel = foam_structure.kernel(KERNEL_REACH, structure)
    early = np.nonzero(kernel[:KERNEL_SAMPLES])[0]
    weights = kernel_weights(KERNEL_REACH)
    ends = range(KERNEL_SEGMENT, KERNEL_REACH + 1, KERNEL_SEGMENT)
    sums = [f"{{ {end}, {real(np.sum(weights[:end] * kernel[:end]))}, {real(np.sum(kernel[:end] ** 2))} }}" for end in ends]
    parts = [f"inline constexpr KernelSample diffuserKernel[] {{\n{rows([f'{{ {int(index)}, {real(kernel[index])} }}' for index in early], 3)}\n}};\n",
             f"inline constexpr KernelSum diffuserKernelSums[] {{\n{rows(sums, 2)}\n}};\n"]
    entries = []
    for v in golden_cases():
        name = v["name"]
        if v["impulses"]:
            items = [f"{{ {frame}, {channel}, {single(amplitude)} }}" for frame, channel, amplitude in v["impulses"]]
            parts.append(f"inline constexpr Impulse {name}Impulses[] {{\n{rows(items, 4)}\n}};\n")
        if len(v["programme"]):
            parts.append(f"inline constexpr float {name}Programme[] {{\n{rows([single(s) for s in v['programme'].reshape(-1)], 8)}\n}};\n")
        if v["changes"]:
            items = [f"{{ {block}LL, {single(value)} }}" for block, value in v["changes"]]
            parts.append(f"inline constexpr MacroChange {name}Changes[] {{\n{rows(items, 3)}\n}};\n")
        found = ([(start, v["model"][start:start + EXCERPT_FRAMES].astype(np.float32)) for start in v["excerptStarts"]]
                 if "excerptStarts" in v else excerpts_of(name, v["rate"], v["model"], v["dry"]))
        for index, (start, piece) in enumerate(found):
            parts.append(f"inline constexpr float {name}Model{index}[] {{\n{rows([single(s) for s in piece.reshape(-1)], 8)}\n}};\n")
        impulses = f"{name}Impulses" if v["impulses"] else "{}"
        programme = f"{name}Programme" if len(v["programme"]) else "{}"
        changes = f"{name}Changes" if v["changes"] else "{}"
        excerpts = ", ".join(f"Excerpt {{ {start}, {name}Model{index} }}" for index, (start, _) in enumerate(found))
        entries.append(f"""    {{ "{name}", {v['rate']}, {single(v['macro'])}, {v['firstFrame']}LL, {v['origin']}LL,
      {impulses}, {v['programmeFirst']}, {programme}, {v['noiseFrames']}, {changes},
      {{ {excerpts} }} }}""")
    body = f"""#pragma once

#include <array>
#include <span>

namespace amanita::dsp::spumegolden
{{
struct Impulse
{{
    int frame;
    int channel;
    float amplitude;
}};

// A sample of the diffuser's answer to a unit impulse.
struct KernelSample
{{
    int sample;
    double value;
}};

// Over the first `samples` samples of that answer: its sum under weights that
// are a hash of the sample's index (the noise of the tests, channel 0), which
// moves when any sample of the answer does, and its energy.
struct KernelSum
{{
    int samples;
    double weightedSum;
    double energy;
}};

// A value of Macro and the internal sample, counted from the instance's first
// frame, at which the first block of 44 that uses it begins.
struct MacroChange
{{
    long long firstBlockSample;
    float macro;
}};

// Frames `firstFrame` and on of the engine's wet output, as the campaign's
// model renders them: left and right interleaved.
struct Excerpt
{{
    int firstFrame;
    std::span<const float> model;
}};

// A fresh instance of the engine with the Spume layer at the reference's
// Decay {real(DECAY_SECONDS)} s and Size {real(SIZE_PERCENT)} %. The engine's first frame is frame `firstFrame` of the
// instance's count, and the oscillators of the base have the origin `origin`.
// The stimulus: impulses, or a programme block (left and right interleaved)
// that starts at `programmeFirstFrame`, or over the first `noiseFrames` frames
// the hashed noise of the tests at `noiseAmplitude` (channel `noiseChannel` on
// the left, the next on the right); silence elsewhere. Frames count from the
// engine's first. Macro is `macro` from the start and then moves as `changes`
// say.
struct Vector
{{
    const char* name;
    int hostRate;
    float macro;
    long long firstFrame;
    long long origin;
    std::span<const Impulse> impulses;
    int programmeFirstFrame;
    std::span<const float> programme;
    int noiseFrames;
    std::span<const MacroChange> changes;
    std::array<Excerpt, {EXCERPTS}> excerpts;
}};

inline constexpr float noiseAmplitude = {single(F(MOTION_AMPLITUDE))};
inline constexpr int noiseChannel = {MOTION_CHANNEL};

// What the reference works with at those knob positions.
inline constexpr float decaySeconds = {single(ENGINE_DECAY_SECONDS)};
inline constexpr float sizeScale = {single(ENGINE_SIZE_SCALE)};

// The diffuser alone, one channel: every sample of its answer to a unit impulse
// that is not zero among the first {KERNEL_SAMPLES}, and its weighted sum and energy up to
// every {KERNEL_SEGMENT} samples, as far as {KERNEL_REACH}.
inline constexpr int diffuserKernelSamples = {KERNEL_SAMPLES};
{chr(10).join(parts)}
inline constexpr Vector vectors[] {{
{("," + chr(10)).join(entries)}
}};
}} // namespace amanita::dsp::spumegolden
"""
    title = ["Golden vectors of the Spume layer, from the campaign's model of the reference's Foam mode",
             "(foam_structure.kernel for the diffuser alone, foam_model for the renders)."]
    return head(title) + body


# ---------------------------------------------------------------- the engine's renderer against the model

def engine_nulls(tool: Path) -> int:
    """Whole renders of the golden cases through the engine's renderer against the model, in decibels."""
    import subprocess
    import tempfile

    from scipy.io import wavfile

    def null(candidate, reference) -> float:
        return float(10 * np.log10((np.sum((candidate - reference) ** 2) + 1e-300) / (np.sum(reference ** 2) + 1e-300)))

    if not tool.exists():
        raise SystemExit(f"{tool} is missing: build the target AmanitaOceanFathomRender")
    worst = -400.0
    with tempfile.TemporaryDirectory() as folder:
        source, target = Path(folder) / "in.wav", Path(folder) / "out.wav"
        for v in golden_cases():
            wavfile.write(source, v["rate"], v["x"])
            renders = {}
            for label, value in (("layer", float(v["macro"])), ("base", 0.0)):
                command = [str(tool), "--input", str(source), "--output", str(target), "--layer", "spume",
                           "--decay", repr(float(ENGINE_DECAY_SECONDS)), "--size", repr(float(ENGINE_SIZE_SCALE)),
                           "--macro", repr(value), "--first-frame", str(v["firstFrame"]),
                           "--oscillator-origin", str(v["origin"])]
                if label == "layer" and v["changes"]:
                    command += ["--macro-at-blocks", ",".join(f"{block}:{value!r}" for block, value in v["changes"])]
                subprocess.run(command, check=True)
                renders[label] = wavfile.read(target)[1].astype(np.float64)[:v["frames"]]
            whole = null(renders["layer"], v["model"])
            base_alone = null(renders["base"], v["plain"])
            worst = max(worst, whole, base_alone)
            line = f"{v['name']:16} with the layer {whole:8.2f} dB   the base alone {base_alone:8.2f} dB"
            if not v["changes"]:
                # What the diffuser adds: the render less the base at the plain input's gain. The network is
                # linear in its input, so that is the base's answer to the diffused input alone.
                share = float(np.cos(0.5 * np.pi * float(v["macro"])))
                diffused = null(renders["layer"] - share * renders["base"], v["model"] - v["dry"])
                worst = max(worst, diffused)
                line += f"   the diffused part alone {diffused:8.2f} dB"
            print(line)
    print(f"worst {worst:.2f} dB")
    return 0


def main() -> int:
    if "--engine" in sys.argv[1:]:
        at = sys.argv.index("--engine")
        given = sys.argv[at + 1] if len(sys.argv) > at + 1 else None
        return engine_nulls(Path(given) if given else ROOT / "build-spume-dsp" / "AmanitaOceanFathomRender")
    check = "--check" in sys.argv[1:]
    only = [a for a in sys.argv[1:] if a in ("--constants", "--golden")]
    jobs = []
    if not only or "--constants" in only:
        jobs.append((CONSTANTS_HEADER, constants_header))
    if not only or "--golden" in only:
        jobs.append((GOLDEN_HEADER, golden_header))
    stale = 0
    for path, make in jobs:
        text = make()
        if check:
            same = path.exists() and path.read_text() == text
            print(f"{'ok   ' if same else 'STALE'} {path.relative_to(ROOT)}")
            stale += not same
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
