#!/usr/bin/env python3
"""C++ headers of the Fathom engine, generated from the campaign's constants and golden vectors.

    python emit_engine_header.py            write both headers
    python emit_engine_header.py --check    exit 1 when a header on disk is not what the data files give

    Source/dsp/FathomEngineConstants.h  from tide_structural_data/engine_constants.json: every constant of the
                                        model the engine uses (SPEC.md), in processing order
    Tests/FathomGoldenVectors.h         from tide_structural_data/engine_golden.json and engine_golden.npz:
                                        the capture vectors (stimulus, the model's excerpts and, above
                                        Macro 0, the voice phase of the capture), the rate table, the
                                        converter vectors and the vectors of the outer laws

The head of each header carries the SHA-256 of the files it was made from. The output depends on nothing
else: no time stamp, no machine, no order of a dictionary. A double-precision number is written with the
shortest digits that read back as the same double, a single-precision number with the shortest digits that
read back as the same float and an `f`; both are checked on the way out.

What the engine does not use stays in the data file: the reference's own knob laws and the reference's
excerpts of the capture vectors.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
DATA = HERE / "tide_structural_data"
CONSTANTS = DATA / "engine_constants.json"
GOLDEN_INDEX = DATA / "engine_golden.json"
GOLDEN_ARRAYS = DATA / "engine_golden.npz"
CONSTANTS_HEADER = ROOT / "Source/dsp/FathomEngineConstants.h"
GOLDEN_HEADER = ROOT / "Tests/FathomGoldenVectors.h"
GENERATOR = "Analyzer/Campaigns/RevOceanCharacterization/emit_engine_header.py"
STANDARD_RATES = ("44100", "48000", "88200", "96000", "176400", "192000")


# ---------------------------------------------------------------- literals

def real(value) -> str:
    """A double-precision literal: the shortest digits that read back as the same double."""
    value = float(value)
    text = repr(value)
    assert float(text) == value and ("." in text or "e" in text or "n" in text)
    return text


def single(value) -> str:
    """A single-precision literal: the shortest digits that read back as the same float."""
    exact = np.float32(value)
    assert float(exact) == float(value), f"{value!r} is not a single-precision number"
    text = str(exact)
    assert np.float32(text) == exact and ("." in text or "e" in text)
    return text + "f"


def rounded(value) -> str:
    """A double-precision number as the single-precision literal nearest to it."""
    return single(np.float32(value))


def rows(items: list, per_line: int, indent: str = "    ") -> str:
    lines = [", ".join(items[start:start + per_line]) for start in range(0, len(items), per_line)]
    return ",\n".join(indent + line for line in lines)


def head(title: list, sources: list) -> str:
    lines = [f"// Generated by {GENERATOR}.", "// Do not edit: change the campaign's data and run the generator again.", "//"]
    lines += [f"// {line}" for line in title]
    lines += ["//", "// Made from (SHA-256):"]
    lines += [f"//   {path.relative_to(ROOT)}  {hashlib.sha256(path.read_bytes()).hexdigest()}" for path in sources]
    return "\n".join(lines) + "\n"


def section(entry: dict) -> str:
    return "{ " + ", ".join(real(v) for v in entry["b"] + entry["a"]) + " }"


# ---------------------------------------------------------------- the constants

def constants_header() -> str:
    c = json.loads(CONSTANTS.read_text())
    assert c["schema"]["version"] == 1
    rule, lines, oscillator, taps, voices = c["converters"]["rule"], c["lines"], c["oscillator"], c["taps"], c["voices"]
    comb, phase, outer, knobs = c["comb"], c["phase"], c["outer"], c["referenceKnobs"]
    assert rule["tableEntries"] == rule["zeroCrossings"] * rule["entriesPerCrossing"]
    assert voices["lines"] == [list(range(1, 9)), list(range(9, 17))]
    assert voices["restLowPass"]["frequency_hz"] == voices["cutoffTopHz"] and voices["restLowPass"]["q"] == voices["restQ"]
    assert outer["levelStage"]["thresholdDbfs"] == 0.0
    assert comb["highPass"]["cornerHz"] < comb["lowPass"]["cornerHz"]
    assert voices["qKnotHz"] == [0.0, 1000.0, 3000.0, 5000.0, 15000.0, 20000.0] and voices["qKnotHz"][-1] == voices["cutoffTopHz"]
    # Q against the cut-off: (Hz, at Macro 0, at Macro 100 %); the last knot is the resting voice
    quality = [(0.0, voices["qAt0Hz"], voices["qAt0Hz"]), (1000.0, voices["qAt1kHz"], voices["qAt1kHz"]),
               (3000.0, *voices["qAt3kHzMacro0And1"]), (5000.0, *voices["qPlateauMacro0And1"]),
               (15000.0, *voices["qPlateauMacro0And1"]), (20000.0, voices["restQ"], voices["restQ"])]
    knots = ["{ " + ", ".join(real(value) for value in knot) + " }" for knot in quality]
    signs = [f"{{ {rate}, {pair[0]}, {pair[1]} }}" for rate, pair in sorted(c["converters"]["measuredClockSigns"].items(), key=lambda item: int(item[0]))]
    primes = ["{ " + ", ".join(str(value) for value in group) + " }" for group in lines["prime"]]
    phases = ["{ " + ", ".join(single(value) for value in group) + " }" for group in oscillator["startPhaseSingle"]]
    body = f"""#pragma once

#include <array>

namespace amanita::dsp::fathom
{{
// Second-order section: y[n] = b0 x[n] + b1 x[n-1] + b2 x[n-2] - a1 y[n-1] - a2 y[n-2].
struct Section
{{
    double b0, b1, b2, a1, a2;
}};

// Rounding sign of the clocks of the two rate converters at a host rate where
// it was measured: -1 a hair low, 0 exact, +1 a hair high.
struct ClockSigns
{{
    int hostRate, input, output;
}};

// Q a voice moves towards at a cut-off, at the two ends of Macro.
struct QualityKnot
{{
    double cutoffHz, atMacro0, atMacro100;
}};

// Timing (SPEC.md, section 1).
inline constexpr int internalRate = {c["internalRateHz"]};
inline constexpr int latencyInternalSamples = {c["timing"]["reportedLatencyInternalSamples"]};
inline constexpr int lineWriteDelaySamples = {c["timing"]["lineWriteDelaySamples"]};

// Rate converters (section 3).
inline constexpr double converterCutoff = {real(rule["cutoff"])};
inline constexpr int converterZeroCrossings = {rule["zeroCrossings"]};
inline constexpr double converterKaiserBeta = {real(rule["kaiserBeta"])};
inline constexpr int converterEntriesPerCrossing = {rule["entriesPerCrossing"]};
inline constexpr int converterTableEntries = {rule["tableEntries"]};
inline constexpr int converterEntriesDroppedAfter = {rule["entriesDroppedOnTheWingAfter"]};
inline constexpr int converterLookaheadMargin = {rule["lookaheadMarginSamples"]};
inline constexpr double converterClockDrift = {real(rule["clockDrift"])};
inline constexpr std::array<ClockSigns, {len(signs)}> measuredClockSigns {{{{
{rows(signs, 3)}
}}}};

// Input equaliser (section 5).
inline constexpr std::array<Section, {len(c["equaliser"]["sections"])}> equaliser {{{{
{rows([section(entry) for entry in c["equaliser"]["sections"]], 1)}
}}}};

// Tide input stage (section 6): the comb of each input. Its delay is a
// single-precision triangle. In its loop sit a high-pass,
// y[n] = gain (x[n] - x[n-1]) + pole y[n-1], and a low-pass,
// y[n] = gain (x[n] + x[n-1]) + pole y[n-1].
inline constexpr float combDelayMidSamples = {single(comb["delayMidSingle"])};
inline constexpr float combDelaySwingSamples = {single(comb["delaySwingSingle"])};
inline constexpr double combPeriodSamples = {real(comb["periodSamples"])};
inline constexpr double combOriginSamples = {real(comb["originSamples"])};
inline constexpr double combRightInputLead = {real(comb["rightInputLeadPeriods"])};
inline constexpr double combFeedback = {real(comb["feedback"])};
inline constexpr double combHighPassGain = {real(comb["highPass"]["highPass"]["gain"])};
inline constexpr double combHighPassPole = {real(comb["highPass"]["highPass"]["pole"])};
inline constexpr double combLowPassGain = {real(comb["lowPass"]["lowPass"]["gain"])};
inline constexpr double combLowPassPole = {real(comb["lowPass"]["lowPass"]["pole"])};

// Lines: lengths in internal samples and input gains (sections 7 and 8).
inline constexpr int groupCount = {len(lines["prime"])};
inline constexpr int lineCount = {len(lines["prime"][0])};
inline constexpr std::array<std::array<int, lineCount>, groupCount> linePrimes {{{{
{rows(primes, 1)}
}}}};
inline constexpr std::array<double, lineCount> lineOwnGain {{
{rows([real(value) for value in lines["ownGain"]], 4)}
}};
inline constexpr std::array<double, lineCount> lineCrossGain {{
{rows([real(value) for value in lines["crossGain"]], 4)}
}};

// Line oscillators, single precision as measured (section 8).
inline constexpr float oscillatorDepthSamples = {single(oscillator["depthSamplesSingle"])};
inline constexpr float oscillatorIncrement = {single(oscillator["incrementSingle"])};
inline constexpr float oscillatorTwoPi = {single(oscillator["twoPiSingle"])};
inline constexpr double oscillatorHalfPi = {real(oscillator["halfPi"])};
inline constexpr double oscillatorHalfPiSingle = {real(oscillator["halfPiSingle"])};
inline constexpr std::array<std::array<float, lineCount>, groupCount> oscillatorStartPhase {{{{
{rows(phases, 1)}
}}}};

// Output taps (section 10).
inline constexpr double tapDecayLowSeconds = {real(taps["decayLowSeconds"])};
inline constexpr double tapDecayKneeSeconds = {real(taps["decayKneeSeconds"])};
inline constexpr double tapFirstAtLow = {real(taps["first"][0])};
inline constexpr double tapFirstAtKnee = {real(taps["first"][1])};
inline constexpr double tapLastAtLow = {real(taps["last"][0])};
inline constexpr double tapLastAtKnee = {real(taps["last"][1])};
inline constexpr double tapLastDecayShape = {real(taps["lastDecayShape"])};
inline constexpr double tapEarlyShape = {real(taps["earlyShape"])};
inline constexpr double tapLateShape = {real(taps["lateShape"])};

// Feedback (section 11).
inline constexpr double feedbackScale = {real(c["feedback"]["scale"])};
inline constexpr std::array<Section, {len(c["feedback"]["kernel"])}> loopKernel {{{{
{rows([section(entry) for entry in c["feedback"]["kernel"]], 1)}
}}}};

// Voices (section 12): the first lines of a group feed one, the others the
// second, half a cycle later. Cut-off, Q and gain are set once per block.
inline constexpr int voiceLineCount = {len(voices["lines"][0])};
inline constexpr int voiceBlockSamples = {c["timing"]["voiceBlockSamples"]};
inline constexpr double voiceSecondOffsetCycles = {real(voices["voiceBOffsetCycles"])};
inline constexpr double voiceRestCutoffHz = {real(voices["cutoffTopHz"])};
inline constexpr double voiceRestQ = {real(voices["restQ"])};
inline constexpr double voiceAmountPerMacro = {real(voices["amountPerMacro"])};
inline constexpr double voiceFullDepthAmount = {real(voices["fullDepthAmount"])};
inline constexpr double voiceCurveBend = {real(voices["curveBend"])};
inline constexpr double voiceCutoffEndHz = {real(voices["cutoffEndHz"])};
inline constexpr double voiceGainTop = {real(voices["gainTop"])};
inline constexpr std::array<QualityKnot, {len(knots)}> voiceQualityKnots {{{{
{rows(knots, 3)}
}}}};
inline constexpr double voiceQualitySmoothing = {real(voices["qSmoothingCoefficient"])};

// Phase of the voices (section 13): its rate against Macro, and per output the
// grid, the bounds and the start law of its wandering level.
inline constexpr double phaseRateAtMacro0 = {real(phase["rateAtMacro0"])};
inline constexpr double phaseRateAtMacro100 = {real(phase["rateAtMacro100"])};
inline constexpr double phaseRateShape = {real(phase["rateShape"])};
inline constexpr std::array<double, groupCount> phaseGridHz {{ {", ".join(real(value) for value in phase["gridHz"])} }};
inline constexpr std::array<double, groupCount> phaseLevelLow {{ {", ".join(real(value) for value in phase["levelLow"])} }};
inline constexpr std::array<double, groupCount> phaseLevelHigh {{ {", ".join(real(value) for value in phase["levelHigh"])} }};
inline constexpr double phaseStartSameHalf = {real(phase["startSameHalfProbability"])};

// Outer shell (section 14).
inline constexpr double clipThreshold = {real(outer["clipThreshold"])};
inline constexpr double clipCeiling = {real(outer["clipCeiling"])};
inline constexpr double levelStageKneeDb = {real(outer["levelStage"]["kneeDb"])};
inline constexpr double levelStageSlope = {real(outer["levelStage"]["slope"])};
inline constexpr double levelStageAttackSeconds = {real(outer["levelStage"]["attackSeconds"])};
inline constexpr double levelStageReleaseSeconds = {real(outer["levelStage"]["releaseSeconds"])};

// Upper ends of the reference's own controls (section 2).
inline constexpr float referenceMaximumDecaySeconds = {single(knobs["decaySeconds"]["high"])};
inline constexpr float referenceMaximumSizeScale = {single(knobs["sizePercent"]["high"] / 100.0)};
inline constexpr float referenceMaximumPreDelaySeconds = {single(knobs["preDelayMilliseconds"]["high"] / 1000.0)};
}} // namespace amanita::dsp::fathom
"""
    title = ["Constants of the Fathom engine: the campaign's structural model of the reference",
             "(Analyzer/Campaigns/RevOceanCharacterization/SPEC.md gives their meaning and status)."]
    return head(title, [CONSTANTS]) + body


# ---------------------------------------------------------------- the golden vectors

def identifier(name: str) -> str:
    return "".join(part.capitalize() if index else part for index, part in enumerate(name.replace("/", "_").split("_")))


def float_array(name: str, values, per_line: int = 8) -> str:
    items = [rounded(value) for value in np.asarray(values, dtype=np.float64).ravel()]
    return f"inline constexpr float {name}[] {{\n{rows(items, per_line)}\n}};\n"


def double_array(name: str, values, per_line: int = 4) -> str:
    items = [real(value) for value in np.asarray(values, dtype=np.float64).ravel()]
    return f"inline constexpr double {name}[] {{\n{rows(items, per_line)}\n}};\n"


def golden_header() -> str:
    constants = json.loads(CONSTANTS.read_text())
    index = json.loads(GOLDEN_INDEX.read_text())
    assert index["schema"]["version"] == 1
    vectors, arrays = index["vectors"], np.load(GOLDEN_ARRAYS)
    data, captures = [], []
    for name, entry in vectors.items():
        if entry["kind"] != "capture":
            continue
        label = identifier(name)
        parameters = entry["parameters"]
        phase = "{}"
        if parameters["macro"] != 0.0:
            curve = entry["phase"]
            outputs = []
            for output, side in enumerate(("Left", "Right")):
                knots = [f"{{ {real(seconds)}, {real(cycles)} }}" for seconds, cycles in zip(curve["knotSeconds"][output], curve["knotCycles"][output])]
                data.append(f"inline constexpr PhaseKnot {label}Phase{side}[] {{\n{rows(knots, 3)}\n}};\n")
                outputs.append(f"PhaseCurve {{ {real(curve['rateCyclesPerSecond'][output])}, {label}Phase{side} }}")
            phase = "{ " + ", ".join(outputs) + " }"
        impulses, programme, programme_first = "{}", "{}", 0
        if "impulses" in entry["stimulus"]:
            events = [f"{{ {frame}, {channel}, {single(amplitude)} }}" for frame, channel, amplitude in entry["stimulus"]["impulses"]]
            data.append(f"inline constexpr Impulse {label}Impulses[] {{\n{rows(events, 3)}\n}};\n")
            impulses = f"{label}Impulses"
        else:
            block = arrays[entry["stimulus"]["array"]]
            assert block.dtype == np.float32 and block.shape[1] == 2
            data.append(float_array(f"{label}Programme", block))
            programme, programme_first = f"{label}Programme", entry["stimulus"]["firstFrame"]
        excerpts = []
        for number, excerpt in enumerate(entry["excerpts"]):
            model = arrays[excerpt["model"]]
            assert model.shape == (excerpt["frames"], 2)
            data.append(float_array(f"{label}Model{number}", model))
            excerpts.append(f"Excerpt {{ {excerpt['engineFirstFrame']}, {label}Model{number} }}")
        captures.append(
            f"    CaptureVector {{ \"{name}\", {entry['hostRate']}, {entry['warmupFrames']},\n"
            f"                    {single(parameters['decaySeconds'])}, {single(parameters['sizeScale'])}, {real(parameters['preDelaySeconds'])}, "
            f"{entry['preDelaySamples']},\n"
            f"                    {single(parameters['macro'])}, {phase},\n"
            f"                    {impulses}, {programme_first}, {programme},\n"
            f"                    {{ {', '.join(excerpts)} }} }}")

    rates = []
    for rate in STANDARD_RATES:
        entry = constants["converters"]["rates"][rate]
        signs = entry.get("clockSigns", {"input": 0, "output": 0})
        rates.append(f"{{ {rate}, {entry['latticeStepsPerHostSample']}, {entry['latticeStepsPerInternalSample']}, {entry['reportedLatencySamples']}, "
                     f"{entry.get('inputDelayLatticeSteps', 0)}, "
                     f"{entry.get('outputDelayLatticeSteps', entry.get('outputDelayInternalSamples'))}, {signs['input']}, {signs['output']} }}")

    table = constants["converters"]["table"]
    samples = [f"{{ {position}, {single(value)} }}" for position, value in sorted(table["samples"].items(), key=lambda item: int(item[0]))]

    converter = vectors["converters"]
    data.append(double_array("converterHostNoise", arrays[converter["hostNoise"]]))
    data.append(double_array("converterInternalNoise", arrays[converter["internalNoise"]]))
    converter_rows = []
    for rate, entry in sorted(converter["rates"].items(), key=lambda item: int(item[0])):
        data.append(double_array(f"toInternal{rate}", arrays[entry["toInternal"]["output"]]))
        data.append(double_array(f"toHost{rate}", arrays[entry["toHost"]["output"]]))
        converter_rows.append(f"    ConverterVector {{ {rate}, {entry['toInternal']['hostFirstFrame']}, {entry['toInternal']['internalFirstSample']}, toInternal{rate},\n"
                              f"                      {entry['toHost']['internalFirstSample']}, {entry['toHost']['hostFirstFrame']}, toHost{rate} }}")

    width = vectors["width"]
    stage = vectors["levelStage"]
    assert arrays[stage["input"]].dtype == np.float32 and arrays[stage["reductionDb"]].dtype == np.float32
    data.append(double_array("clipInput", arrays[vectors["clip"]["input"]]))
    data.append(double_array("clipOutput", arrays[vectors["clip"]["output"]]))
    data.append(double_array("widthScale", arrays[width["widthScale"]]))
    data.append(double_array("widthInput", arrays[width["input"]], 2))
    data.append(double_array("widthOutput", arrays[width["output"]], 2))
    data.append(double_array("mixValue", arrays[vectors["mix"]["mix"]]))
    data.append(double_array("mixDryAndWetGain", arrays[vectors["mix"]["dryAndWetGain"]], 2))
    data.append(float_array("levelStageInput", arrays[stage["input"]]))
    data.append(float_array("levelStageReductionDb", arrays[stage["reductionDb"]]))

    body = f"""#pragma once

#include <array>
#include <span>

namespace amanita::dsp::fathomgolden
{{
struct Impulse
{{
    int frame;
    int channel;
    float amplitude;
}};

// Frames `firstFrame` and on of the engine's wet output, as the campaign's
// model renders them: left and right interleaved.
struct Excerpt
{{
    int firstFrame;
    std::span<const float> model;
}};

// The phase of voice A of one output in a capture above Macro 0:
// rate * t + level(t) cycles, t in seconds since the first processed frame.
// The level is that of the first knot before it, moves from knot to knot along
// (1 - cos(pi x)) / 2 and stays at the last knot's.
struct PhaseKnot
{{
    double seconds;
    double cycles;
}};

struct PhaseCurve
{{
    double cyclesPerSecond;
    std::span<const PhaseKnot> knots;
}};

// A fresh instance, `warmupFrames` of silence, then the stimulus: impulses, or
// a programme block (left and right interleaved) that starts at
// `programmeFirstFrame`; silence elsewhere. Above Macro 0 the voices of the
// left and of the right output follow `phase`.
struct CaptureVector
{{
    const char* name;
    int hostRate;
    int warmupFrames;
    float decaySeconds;
    float sizeScale;
    double preDelaySeconds;
    int preDelayFrames;
    float macro;
    std::array<PhaseCurve, 2> phase;
    std::span<const Impulse> impulses;
    int programmeFirstFrame;
    std::span<const float> programme;
    std::array<Excerpt, 2> excerpts;
}};

// The time base of a host rate: lattice steps per host frame and per internal
// sample, reported latency in host frames, delays of the two converters in
// lattice steps and the rounding signs of their clocks.
struct RateTiming
{{
    int hostRate, hostStep, internalStep, latencyFrames;
    long long inputDelay, outputDelay;
    int inputClockSign, outputClockSign;
}};

struct TableSample
{{
    int entry;
    float value;
}};

// Both converters on noise that is zero outside its 96 samples. Host noise
// from host frame `hostFirstFrame` gives the internal samples from
// `toInternalFirstSample`; internal noise from sample `internalFirstSample`
// gives the raw host frames from `toHostFirstFrame`.
struct ConverterVector
{{
    int hostRate;
    int hostFirstFrame;
    int toInternalFirstSample;
    std::span<const double> toInternal;
    int internalFirstSample;
    int toHostFirstFrame;
    std::span<const double> toHost;
}};

{chr(10).join(data)}
inline constexpr std::array<CaptureVector, {len(captures)}> captureVectors {{{{
{(',' + chr(10)).join(captures)}
}}}};

inline constexpr std::array<RateTiming, {len(rates)}> rateTimings {{{{
{rows(rates, 1)}
}}}};

inline constexpr double converterTableSum = {real(table["sum"])};
inline constexpr std::array<TableSample, {len(samples)}> converterTableSamples {{{{
{rows(samples, 3)}
}}}};

inline constexpr std::array<ConverterVector, {len(converter_rows)}> converterVectors {{{{
{(',' + chr(10)).join(converter_rows)}
}}}};

// Level stage: the reduction in dB after each of the input frames (left and
// right interleaved) at this host rate, from rest.
inline constexpr int levelStageHostRate = {stage["hostRate"]};
}} // namespace amanita::dsp::fathomgolden
"""
    title = ["Golden vectors of the Fathom engine, from the campaign's model of the reference",
             "(Analyzer/Campaigns/RevOceanCharacterization/SPEC.md, section 19)."]
    return head(title, [CONSTANTS, GOLDEN_INDEX, GOLDEN_ARRAYS]) + body


# ---------------------------------------------------------------- files

HEADERS = ((CONSTANTS_HEADER, constants_header), (GOLDEN_HEADER, golden_header))


def main() -> None:
    if sys.argv[1:] not in ([], ["--check"]):
        raise SystemExit(__doc__)
    stale = []
    for path, build in HEADERS:
        text = build()
        if sys.argv[1:]:
            current = path.read_text() if path.exists() else None
            print(f"{path.relative_to(ROOT)}: {'up to date' if current == text else 'differs from the data files'}")
            stale += [] if current == text else [path]
        else:
            path.write_text(text)
            print(f"{path.relative_to(ROOT)}: {len(text)} bytes, SHA-256 {hashlib.sha256(text.encode()).hexdigest()}")
    if stale:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
