#!/usr/bin/env python3
"""Structural model of the first pass of Rev OCEAN (Tide, Macro 0, Size 100 %, Decay 0.5 s, 48 kHz).

    predict(time, input_channel) -> array (2500, 2)

is the unit-impulse response for an impulse on `input_channel` at host sample
`time` (counted from the first sample after the 10 s warm-up); index n is the
output n samples after the impulse, raw (it contains the reported latency).
Only [1150, 2500) is filled: nothing arrives earlier.

Signal path of the model (all constants in tide_structural_data/first_order_a.npz,
regenerated by fit_first_order_a.py; findings/first_order_a.md has the evidence):

    host impulse -> ideal 48 k -> 44.1 k conversion -> pre kernel (44.1 kHz lattice)
      -> per output channel a bank of delay lines of prime length (44.1 kHz samples),
         each read with linear interpolation at  prime + A sin(phase),  the phase
         being a float32 accumulator stepped once per 44.1 kHz sample
      -> second pass: line a feeding line b of the same channel (no extra delay)
      -> ideal 44.1 k -> 48 k conversion -> post kernel (48 kHz FIR)

The module only evaluates the model; it renders nothing.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import numpy as np
from scipy.signal import fftconvolve

DATA = Path(__file__).resolve().parent / "tide_structural_data" / "first_order_a.npz"

HOST_RATE = 48000
INTERNAL_RATE = 44100
RATIO = INTERNAL_RATE / HOST_RATE            # 147/160: internal samples per host sample
RESPONSE_LENGTH = 2500
FILL_START = 1150

LFO_HZ = 0.6
LFO_INCREMENT = np.float32(2.0 * np.pi * LFO_HZ / INTERNAL_RATE)
TWO_PI = np.float32(2.0 * np.pi)
MODULATION_SECONDS = 0.88e-3                 # depth of every line: 38.808 internal samples
# Delay of line n of the left and of the right network, internal samples (all prime).
PRIMES = np.array([[1031, 1097, 1187, 1289, 1423, 1583, 1783, 2027, 2333],
                   [1039, 1109, 1193, 1301, 1429, 1597, 1787, 2039, 2333]])
LATENCY = 187                                # internal samples common to every path
WARMUP_INTERNAL = 441000                     # the 10 s warm-up of the campaign
SHIFT_HALF_WIDTH = 96                        # half width of the windowed sinc that shifts the pre kernel
SHIFT_KAISER_BETA = 8.0


def _advance(phase: np.float32) -> np.float32:
    following = np.float32(phase + LFO_INCREMENT)
    return np.float32(following - TWO_PI) if following >= TWO_PI else following


def lfo_segments(start: float, steps: int) -> tuple:
    """Exact piecewise-linear form of the accumulator `phase += inc; if phase >= 2 pi: phase -= 2 pi` in float32.

    Returns (index, phase, step): for index[j] <= k < index[j + 1] the phase after k
    steps is phase[j] + (k - index[j]) * step[j], bit for bit what the float32 loop gives.
    """
    index = [0]
    phases = [float(np.float32(start))]
    increments = [0.0]
    k = 0
    phase = np.float32(start)
    wrap = float(TWO_PI)
    while k < steps:
        one = _advance(phase)
        two = _advance(one)
        three = _advance(two)
        k += 1
        phase = one
        index.append(k)
        phases.append(float(phase))
        increments.append(0.0)
        step = float(two) - float(one)
        exponent = np.frexp(float(one))[1]
        if step <= 0 or np.frexp(float(three))[1] != exponent or float(three) - float(two) != step:
            continue
        # Two equal steps inside one binade: every further step there rounds the same way
        # (a tie rounds to even, and the mantissa is even from then on).
        top = min(float(np.ldexp(1.0, int(exponent))), wrap)
        count = int(np.floor((top - float(phase)) / step))
        while count > 0 and float(phase) + count * step >= top:
            count -= 1
        count = min(count, steps - k)
        if count <= 0:
            continue
        increments[-1] = step
        k += count
        phase = np.float32(float(phase) + count * step)
        index.append(k)
        phases.append(float(phase))
        increments.append(0.0)
    return np.array(index), np.array(phases), np.array(increments)


def lfo_phase(segments: tuple, k: np.ndarray) -> np.ndarray:
    index, phases, increments = segments
    j = np.searchsorted(index, k, side="right") - 1
    return phases[j] + (k - index[j]) * increments[j]


class Model:
    """Constants of the first-pass model and its evaluation."""

    def __init__(self, constants: dict):
        self.pre = np.asarray(constants["pre"], float)             # pre kernel, lattice taps -half..half
        self.post = np.asarray(constants["post"], float)           # post kernel, host lags post_first_lag..
        self.post_first_lag = int(constants["post_first_lag"])
        self.first_gain = np.asarray(constants["first_gain"], float)      # [output, line, input]
        self.second_pairs = np.asarray(constants["second_pairs"], int)    # rows (output, source line, target line)
        self.second_gain = np.asarray(constants["second_gain"], float)    # [pair, input]
        self.lfo_start = float(constants["lfo_start"])             # phase of line L1 at the origin
        self.lfo_step = float(constants["lfo_step"])               # phase decrement from line to line
        self.lfo_origin = int(constants["lfo_origin"])             # accumulator steps taken at lattice time 0
        self.depth = float(constants.get("depth", MODULATION_SECONDS * INTERNAL_RATE))
        self.pre_half = (len(self.pre) - 1) // 2
        self._segments = {}

    def segments(self, output: int, line: int) -> tuple:
        """Accumulator of line `line` of network `output`; lines are numbered L1, R1, L2, R2, ..."""
        key = (output, line)
        if key not in self._segments:
            start = (self.lfo_start - (2 * line + output) * self.lfo_step) % (2.0 * np.pi)
            self._segments[key] = lfo_segments(start, self.lfo_origin + int(112 * INTERNAL_RATE))
        return self._segments[key]

    def delay(self, output: int, line: int, lattice: np.ndarray, origin: int) -> np.ndarray:
        """Modulated part of a line's delay when it is read at lattice time `lattice` (internal samples)."""
        phase = lfo_phase(self.segments(output, line), self.lfo_origin + origin + lattice)
        return PRIMES[output, line] + self.depth * np.sin(phase)

    def shifted_pre(self, fraction: float) -> np.ndarray:
        """Pre kernel for a pulse that sits `fraction` of an internal sample after a lattice point."""
        if fraction == 0.0:
            return self.pre
        half = self.pre_half + SHIFT_HALF_WIDTH
        position = np.arange(-half, half + 1)[:, None] - fraction - np.arange(-self.pre_half, self.pre_half + 1)[None, :]
        inside = np.abs(position) <= SHIFT_HALF_WIDTH + 1
        window = np.where(inside, np.i0(SHIFT_KAISER_BETA * np.sqrt(np.clip(1.0 - (position / (SHIFT_HALF_WIDTH + 1)) ** 2, 0.0, 1.0)))
                          / np.i0(SHIFT_KAISER_BETA), 0.0)
        return (window * np.sinc(position)) @ self.pre

    @staticmethod
    def read(source: np.ndarray, source_first: int, position: np.ndarray) -> np.ndarray:
        """Linear interpolation of `source` (lattice index source_first + i) at fractional positions."""
        base = np.floor(position).astype(np.int64)
        fraction = position - base
        i = base - source_first
        valid = (i >= 0) & (i + 1 < len(source))
        out = np.zeros(len(position))
        out[valid] = (1.0 - fraction[valid]) * source[i[valid]] + fraction[valid] * source[i[valid] + 1]
        return out

    def first_pass(self, output: int, line: int, pre: np.ndarray, origin: int) -> tuple:
        """(first lattice index, samples) of a line's output for the pre-filtered pulse at lattice time 0."""
        half = (len(pre) - 1) // 2
        centre = LATENCY + PRIMES[output, line]
        lattice = np.arange(int(centre - self.depth) - half - 2, int(centre + self.depth) + half + 3)
        position = lattice - LATENCY - self.delay(output, line, lattice, origin)
        return int(lattice[0]), self.read(pre, -half, position)

    def second_pass(self, output: int, source: int, target: int, pre: np.ndarray, origin: int) -> tuple:
        """Output of line `target` fed by the output of line `source` of the same network."""
        half = (len(pre) - 1) // 2
        first, samples = self.first_pass(output, source, pre, origin)
        centre = LATENCY + PRIMES[output, source] + PRIMES[output, target]
        lattice = np.arange(int(centre - 2 * self.depth) - half - 3, int(centre + 2 * self.depth) + half + 4)
        position = lattice - self.delay(output, target, lattice, origin)
        return int(lattice[0]), self.read(samples, first, position)

    def lattice_signals(self, time: int, lines: range = range(8)) -> tuple:
        """Internal-rate signal of each output for each input: (first lattice index, y[input, output, lattice], fraction)."""
        internal = time * INTERNAL_RATE
        origin, remainder = divmod(internal, HOST_RATE)
        fraction = remainder / HOST_RATE
        pre = self.shifted_pre(fraction)
        half = (len(pre) - 1) // 2
        first = LATENCY + int(PRIMES.min() - self.depth) - half - 4
        last = int((RESPONSE_LENGTH + 64) * RATIO) + half + 4
        y = np.zeros((2, 2, last - first))

        def add(output, start, samples, gains):
            lo = max(start, first)
            hi = min(start + len(samples), last)
            if hi > lo:
                y[:, output, lo - first:hi - first] += gains[:, None] * samples[None, lo - start:hi - start]

        for output in (0, 1):
            for line in lines:
                start, samples = self.first_pass(output, line, pre, origin)
                add(output, start, samples, self.first_gain[output, line])
        for (output, source, target), gains in zip(self.second_pairs, self.second_gain):
            start, samples = self.second_pass(int(output), int(source), int(target), pre, origin)
            add(int(output), start, samples, gains)
        return first, y, fraction

    def responses(self, time: int) -> np.ndarray:
        """Unit-impulse responses [input, sample after the impulse, output] for an impulse at host sample `time`."""
        first, y, fraction = self.lattice_signals(time)
        lags = self.post_first_lag + np.arange(len(self.post))
        host = np.arange(FILL_START - lags[-1], RESPONSE_LENGTH - lags[0])
        used = np.nonzero(np.any(y != 0.0, axis=(0, 1)))[0]
        lattice = first + used
        # Ideal conversion to the host rate: band-limited to the internal Nyquist frequency.
        interpolation = np.sinc(host[:, None] * RATIO + fraction - lattice[None, :])
        ideal = np.einsum("hl,iol->ioh", interpolation, y[:, :, used])
        full = fftconvolve(ideal, self.post[None, None, :], mode="full", axes=-1)
        start = FILL_START - (int(host[0]) + int(lags[0]))
        out = np.zeros((2, RESPONSE_LENGTH, 2))
        out[:, FILL_START:, :] = full[:, :, start:start + RESPONSE_LENGTH - FILL_START].transpose(0, 2, 1)
        return out


def load(path: Path = DATA) -> Model:
    with np.load(path) as constants:
        return Model({key: constants[key] for key in constants.files})


@lru_cache(maxsize=1)
def model() -> Model:
    return load()


@lru_cache(maxsize=4)
def _responses(time: int) -> np.ndarray:
    return model().responses(time)


def predict(time: int, input_channel: int) -> np.ndarray:
    """Raw unit-impulse response (2500, 2) of the reference for an impulse on `input_channel` at `time`."""
    if input_channel not in (0, 1):
        raise ValueError("input_channel is 0 or 1")
    return _responses(int(time))[input_channel].copy()
