// Generated by Analyzer/Campaigns/RevOceanCharacterization/emit_engine_header.py.
// Do not edit: change the campaign's data and run the generator again.
//
// Constants of the Fathom engine: the campaign's structural model of the reference
// (Analyzer/Campaigns/RevOceanCharacterization/SPEC.md gives their meaning and status).
//
// Made from (SHA-256):
//   Analyzer/Campaigns/RevOceanCharacterization/tide_structural_data/engine_constants.json  68ed935494946863041f259b7dba8095c5c2636e8b7bb63cf2a66e698663f97d
#pragma once

#include <array>

namespace amanita::dsp::fathom
{
// Second-order section: y[n] = b0 x[n] + b1 x[n-1] + b2 x[n-2] - a1 y[n-1] - a2 y[n-2].
struct Section
{
    double b0, b1, b2, a1, a2;
};

// Rounding sign of the clocks of the two rate converters at a host rate where
// it was measured: -1 a hair low, 0 exact, +1 a hair high.
struct ClockSigns
{
    int hostRate, input, output;
};

// Q a voice moves towards at a cut-off, at the two ends of Macro.
struct QualityKnot
{
    double cutoffHz, atMacro0, atMacro100;
};

// Timing (SPEC.md, section 1).
inline constexpr int internalRate = 44100;
inline constexpr int latencyInternalSamples = 44;
inline constexpr int lineWriteDelaySamples = 44;

// Rate converters (section 3).
inline constexpr double converterCutoff = 0.9;
inline constexpr int converterZeroCrossings = 17;
inline constexpr double converterKaiserBeta = 6.0;
inline constexpr int converterEntriesPerCrossing = 4096;
inline constexpr int converterTableEntries = 69632;
inline constexpr int converterEntriesDroppedAfter = 1;
inline constexpr int converterLookaheadMargin = 10;
inline constexpr double converterClockDrift = 1.1641532182693481e-10;
inline constexpr std::array<ClockSigns, 8> measuredClockSigns {{
    { 48000, -1, 1 }, { 56000, -1, -1 }, { 64000, -1, -1 },
    { 88200, 0, 0 }, { 96000, -1, 1 }, { 176400, 0, 0 },
    { 192000, 1, -1 }, { 384000, 1, -1 }
}};

// Input equaliser (section 5).
inline constexpr std::array<Section, 2> equaliser {{
    { 1.001981819721075, -1.9323225733505953, 0.9311255177452129, -1.9323225733505953, 0.9331073374662877 },
    { 0.9865209110346379, -1.4711369258407723, 0.531559170653515, -1.4711369258407723, 0.5180800816881529 }
}};

// Tide input stage (section 6): the comb of each input. Its delay is a
// single-precision triangle. In its loop sit a high-pass,
// y[n] = gain (x[n] - x[n-1]) + pole y[n-1], and a low-pass,
// y[n] = gain (x[n] + x[n-1]) + pole y[n-1].
inline constexpr float combDelayMidSamples = 431.2075f;
inline constexpr float combDelaySwingSamples = 236.036f;
inline constexpr double combPeriodSamples = 8820000.0;
inline constexpr double combOriginSamples = 85.7;
inline constexpr double combRightInputLead = 0.25;
inline constexpr double combFeedback = -0.4;
inline constexpr double combHighPassGain = 0.9978674165185535;
inline constexpr double combHighPassPole = 0.995734833037107;
inline constexpr double combLowPassGain = 0.8717750754522837;
inline constexpr double combLowPassPole = -0.7435501509045674;

// Lines: lengths in internal samples and input gains (sections 7 and 8).
inline constexpr int groupCount = 2;
inline constexpr int lineCount = 16;
inline constexpr std::array<std::array<int, lineCount>, groupCount> linePrimes {{
    { 1031, 1097, 1187, 1289, 1423, 1583, 1783, 2027, 2333, 2699, 3163, 3719, 4409, 5261, 6299, 7589 },
    { 1039, 1109, 1193, 1301, 1429, 1597, 1787, 2039, 2333, 2707, 3163, 3719, 4409, 5261, 6299, 7589 }
}};
inline constexpr std::array<double, lineCount> lineOwnGain {
    0.15516979409611897, 0.1329956962803885, 0.1188285613217364, 0.1097771124373413,
    0.10399409934782582, 0.10029930519711648, 0.1539916413642996, 0.1454880425232644,
    0.13780798459307697, 0.12966022782217296, 0.1205808502701082, 0.11012816229782259,
    0.09765879191023535, 0.08224079919221555, 0.06253300178652335, 0.03662007140668407
};
inline constexpr std::array<double, lineCount> lineCrossGain {
    0.08880786957702407, 0.07611703372022234, 0.06800879924703153, 0.06282841026288087,
    0.05951863547579968, 0.057404004861242766, 0.0, 0.006132196326825874,
    0.012128168856837531, 0.01790452311353223, 0.023272231971537324, 0.027915495178556696,
    0.03129207768954725, 0.03247823253902127, 0.029910660512870564, 0.020958657220177677
};

// Line oscillators, single precision as measured (section 8).
inline constexpr float oscillatorDepthSamples = 38.808002f;
inline constexpr float oscillatorIncrement = 8.548552e-05f;
inline constexpr float oscillatorTwoPi = 6.2831855f;
inline constexpr double oscillatorHalfPi = 1.5707963267948966;
inline constexpr double oscillatorHalfPiSingle = 1.5707963705062866;
inline constexpr std::array<std::array<float, lineCount>, groupCount> oscillatorStartPhase {{
    { 0.0f, 22.5f, 45.0f, 67.5f, 90.0f, 112.5f, 135.0f, 157.5f, 180.0f, 202.5f, 225.0f, 247.5f, 270.0f, 292.5f, 315.0f, 337.5f },
    { 11.25f, 33.75f, 56.25f, 78.75f, 101.25f, 123.75f, 146.25f, 168.75f, 191.25f, 213.75f, 236.25f, 258.75f, 281.25f, 303.75f, 326.25f, 348.75f }
}};

// Output taps (section 10).
inline constexpr double tapDecayLowSeconds = 0.5;
inline constexpr double tapDecayKneeSeconds = 6.0;
inline constexpr double tapFirstAtLow = 0.46;
inline constexpr double tapFirstAtKnee = 0.228;
inline constexpr double tapLastAtLow = 0.336;
inline constexpr double tapLastAtKnee = 0.428;
inline constexpr double tapLastDecayShape = -2.6;
inline constexpr double tapEarlyShape = 4.0;
inline constexpr double tapLateShape = 2.0;

// Feedback (section 11).
inline constexpr double feedbackScale = 0.25;
inline constexpr std::array<Section, 2> loopKernel {{
    { 0.9973522246905882, -1.6690026450940447, 0.6968154327427423, -1.6685904245039256, 0.6945798780234493 },
    { 0.9937298148435365, 0.18010442552892503, -0.2982019962506739, 0.17651929870961477, -0.3008870545878271 }
}};

// Voices (section 12): the first lines of a group feed one, the others the
// second, half a cycle later. Cut-off, Q and gain are set once per block.
inline constexpr int voiceLineCount = 8;
inline constexpr int voiceBlockSamples = 44;
inline constexpr double voiceSecondOffsetCycles = 0.5;
inline constexpr double voiceRestCutoffHz = 20000.0;
inline constexpr double voiceRestQ = 1.0;
inline constexpr double voiceAmountPerMacro = 0.88;
inline constexpr double voiceFullDepthAmount = 0.05;
inline constexpr double voiceCurveBend = 3.0;
inline constexpr double voiceCutoffEndHz = 10.0;
inline constexpr double voiceGainTop = 1.4142135623730951;
inline constexpr std::array<QualityKnot, 6> voiceQualityKnots {{
    { 0.0, 3.365, 3.365 }, { 1000.0, 7.01, 7.01 }, { 3000.0, 10.0, 2.09 },
    { 5000.0, 7.0, 1.36 }, { 15000.0, 7.0, 1.36 }, { 20000.0, 1.0, 1.0 }
}};
inline constexpr double voiceQualitySmoothing = 0.09516258196404048;

// Phase of the voices (section 13): its rate against Macro, and per output the
// grid, the bounds and the start law of its wandering level.
inline constexpr double phaseRateAtMacro0 = 0.0502375;
inline constexpr double phaseRateAtMacro100 = 0.0564238;
inline constexpr double phaseRateShape = 0.63;
inline constexpr std::array<double, groupCount> phaseGridHz { 0.136, 0.16 };
inline constexpr std::array<double, groupCount> phaseLevelLow { 0.184, -0.007 };
inline constexpr std::array<double, groupCount> phaseLevelHigh { 0.591, 0.433 };
inline constexpr double phaseStartSameHalf = 0.83;

// Outer shell (section 14).
inline constexpr double clipThreshold = 2.51188643150958;
inline constexpr double clipCeiling = 3.9810717055349722;
inline constexpr double levelStageKneeDb = 9.98306;
inline constexpr double levelStageSlope = 0.7142857142857143;
inline constexpr double levelStageAttackSeconds = 0.005;
inline constexpr double levelStageReleaseSeconds = 0.3;

// Upper ends of the reference's own controls (section 2).
inline constexpr float referenceMaximumDecaySeconds = 60.0f;
inline constexpr float referenceMaximumSizeScale = 2.0f;
inline constexpr float referenceMaximumPreDelaySeconds = 2.0f;
} // namespace amanita::dsp::fathom
