// Generated by Analyzer/Campaigns/RevOceanCharacterization/emit_spume_header.py.
// Do not edit: change the model or the generator and run it again.
//
// Constants of the Spume layer: the campaign's model of the reference's Foam mode
// (Analyzer/Campaigns/RevOceanCharacterization/foam/findings/FOAM_STATE.md gives their meaning
// and status) and Ocean's own.
//
// Made from (SHA-256):
//   Analyzer/Campaigns/RevOceanCharacterization/foam/model/foam_structure.py  ccbad9f7b57593aa055f284888f28b4388977a8c0ccd9e330b5c53a762d4ea32
//   Analyzer/Campaigns/RevOceanCharacterization/foam/model/structure_final.json  9686b74217b32b20cc935ba5517cc06433ca326ae33e82c8bb1e516f1abfd5bd
//   Analyzer/Campaigns/RevOceanCharacterization/foam/model/foam_model.py  a4596fca91cdfcf9bc35cf531cf2b605a679172dd7a5cf029390949b70af0ac8
//   Analyzer/Campaigns/RevOceanCharacterization/foam/model/fcommon.py  46a22fdd5397eed00086ed0f09b1fdddf0c54f7a93f6b5e4c3b90fd45272e1ee
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/base.py  9b197bb67d8781809daea63e60fad56bdfb16b4aa705d59243f39a2c94b92c8e
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/abyss_core.c  518f04da361a1f71d7e82aa5408c510407d81ba290e4ba173587507158227eca
#pragma once

#include <array>

namespace amanita::dsp::spume
{
// The diffuser (FOAM_STATE.md, section 2): seven stages of four parallel
// Schroeder all-passes, y[n] = g x[n] + x[n - D] - g y[n - D], with one gain
// per stage. The input goes to each of the four paths times `pathInputGain`;
// between two stages the four are mixed by the Sylvester Hadamard matrix of
// order 4 times `mixGain`; the output is their plain sum. Delays in internal
// samples, by stage and path; path 0 takes the sum row of the mix.
inline constexpr int stageCount = 7;
inline constexpr int pathCount = 4;
inline constexpr std::array<std::array<int, pathCount>, stageCount> delaySamples {{
    { 1323, 1457, 1604, 1765 },
    { 2591, 2353, 2137, 1943 },
    { 2851, 3137, 3457, 3803 },
    { 5581, 5071, 4607, 4181 },
    { 6143, 6761, 7439, 8189 },
    { 12013, 10919, 9923, 9013 },
    { 13229, 14561, 16033, 17653 }
}};
inline constexpr std::array<double, stageCount> stageGain {
    0.373, 0.466, 0.572, 0.474, 0.409, 0.363, 0.272
};
inline constexpr double pathInputGain = 0.5;
inline constexpr double mixGain = 0.5;
inline constexpr int longestDelaySamples = 17653;
inline constexpr int totalDelaySamples = 179737;

// Macro (FOAM_STATE.md, section 3): the plain input times cos(pi/2 Macro) and
// the diffused one times sin(pi/2 Macro). Each of the two gains moves once per
// block of `gainBlockSamples` internal samples and is held over it: of what
// separates it from its target, `gainBlockRetention` stays, which is
// exp(-44/441), a one-pole of 10 ms run at the block rate. A block begins at
// the internal samples `gainBlockPhase` modulo `gainBlockSamples`.
inline constexpr int gainBlockSamples = 44;
inline constexpr int gainBlockPhase = 43;
inline constexpr double gainBlockRetention = 0.9050426198534351;

// Ocean's own (nothing of this was measured).
// A gain this near its target has arrived.
inline constexpr double gainFloor = 1e-12;
} // namespace amanita::dsp::spume
