// Generated by Analyzer/Campaigns/RevOceanCharacterization/emit_undertow_header.py.
// Do not edit: change the model or the generator and run it again.
//
// Constants of the Undertow layer: the campaign's model of the reference's Abyss mode
// (Analyzer/Campaigns/RevOceanCharacterization/abyss/findings: ABYSS_STATE.md, tempo.md and
// controls.md give their meaning and status) and Ocean's own.
//
// Made from (SHA-256):
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/abyss_model.py  73faae75fa4eef2eebe0e45adbb4f129250c5e19a9bff4d373b382fc6599a72f
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/hostclock.py  45e6d5030d930647df91932fa14f705fc29753747da8ec446e22c936f366ecc8
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/abyss_core.c  518f04da361a1f71d7e82aa5408c510407d81ba290e4ba173587507158227eca
//   Analyzer/Campaigns/RevOceanCharacterization/abyss/model/base.py  9b197bb67d8781809daea63e60fad56bdfb16b4aa705d59243f39a2c94b92c8e
#pragma once

namespace amanita::dsp::undertow
{
// Raised-cosine fades of a chunk over the position behind its mirror point:
// in over the first `fadeIn` samples, out over the last `fadeOut` samples in
// front of `end`, nothing from `end` on. Internal samples at 120 BPM; the
// three numbers follow the tempo with the chunk, so they are fixed shares of it.
struct Window
{
    double fadeIn, fadeOut, end;
};

// A grain reader: the increment of its single-precision phasor per internal
// sample, the sweep of its delay and its shortest delay in internal samples.
struct GrainReader
{
    float increment;
    double sweepSamples, shortestDelaySamples;
};

// A voice gain against Macro: nothing up to `foot`, the full gain from `knee`,
// a straight line between.
struct Ramp
{
    double foot, knee;
};

// The layer runs at the engine's internal rate in blocks of this many samples.
inline constexpr int blockSamples = 44;

// Reversed readers (ABYSS_STATE.md, section 2; tempo.md, section 4). A chunk
// is a note value, held as a single-precision number of quarter notes.
inline constexpr float unisonChunkQuarters = 1.3333334f;
inline constexpr float octaveUpChunkQuarters = 2.0f;
inline constexpr float octaveDownChunkQuarters = 2.6666667f;
// Tempo at which the windows below and the recirculation delay are given.
inline constexpr double windowTempo = 120.0;
inline constexpr Window unisonWindow { 6036.5, 2075.5, 29400.05 };
inline constexpr Window octaveUpWindow { 12545.78, 5794.48, 44099.96 };
inline constexpr Window octaveDownWindow { 22270.67, 9006.18, 58798.07 };

// Recirculation of the octave-up voice in front of its grain reader: one chunk
// of its reader, in whole internal samples, and the gain of one pass.
inline constexpr double recirculationSamplesAtWindowTempo = 44100.0;
inline constexpr double recirculationGain = 0.198;

// Grain readers. The phasors are single precision and stand at `phasorStart`
// `phasorLeadSamples` in front of their origin. Bit patterns of the
// increments: D 0x38C5C3E0, UL 0x39458B10, UR 0x3946A910.
inline constexpr float phasorStart = 0.5f;
inline constexpr int phasorLeadSamples = 2;
inline constexpr GrainReader octaveDownReader { 9.4301766e-05f, 5313.13373, 45.58356 };
inline constexpr GrainReader octaveUpLeftReader { 0.00018839189f, 5268.90989, 44.52724 };
inline constexpr GrainReader octaveUpRightReader { 0.00018945732f, 5346.74391, 44.53402 };

// Macro (ABYSS_STATE.md, section 4; controls.md, section 3): the gain of each
// voice at full strength, its ramp, and the one-pole on each gain.
inline constexpr double unisonGain = 0.6927952;
inline constexpr double octaveUpLeftGain = 0.487907;
inline constexpr double octaveUpRightGain = 0.487907;
inline constexpr double octaveDownGain = 0.707228;
inline constexpr Ramp unisonRamp { 0.0, 0.3 };
inline constexpr Ramp octaveUpRamp { 0.1461, 0.4596 };
inline constexpr Ramp octaveDownRamp { 0.6041, 1.0 };
inline constexpr double gainSmoothingSeconds = 0.01;

// The reference's arithmetic (tempo.md, sections 3 and 5); a test hook of the
// engine. Converter block m stamps the first internal block that begins at or
// behind the place of m converter blocks, in internal samples, less
// `tickBlockOffset`; a boundary is taken in the block whose stamp lies less
// than `tickCatchSamples` in front of it. With a stopped transport the
// boundaries fall later by a fitted curve whose arithmetic is not known:
// `freeRunDriftSamplesPerQuarter` from `freeRunDriftFromQuarters` on, with the
// sign turning at every doubling of the position.
inline constexpr double tickBlockOffset = 42.2;
inline constexpr double tickCatchSamples = 43.0;
inline constexpr double freeRunDriftSamplesPerQuarter = 4.93e-05;
inline constexpr double freeRunDriftFromQuarters = 512.0;
// The 32 accumulators of the base repeat after `oscillatorPeriodSteps` steps
// once `oscillatorSettleSteps` have been made.
inline constexpr long long oscillatorSettleSteps = 26000000;
inline constexpr long long oscillatorPeriodSteps = 13159175;

// Ocean's own (nothing of this was measured).
inline constexpr double minimumTempo = 20.0;
inline constexpr double maximumTempo = 999.0;
inline constexpr double fallbackTempo = 120.0;
// A chunk that is cut while its window is above the floor fades out.
inline constexpr double cutShortFadeSeconds = 0.005;
inline constexpr double cutShortFloor = 0.001;
// The reported position against the one the tempo lets expect. It has jumped
// when it lies `jumpBlocks` internal blocks off, or `positionRate` of the time
// since the host's last word if that is more; it is where it was expected
// within `consistentQuarters`; in between it has drifted and is followed.
inline constexpr double jumpBlocks = 2.0;
inline constexpr double positionRate = 0.04;
inline constexpr double consistentQuarters = 1e-07;
// The tempo. A change by more than `tempoStep` of it that has no other change
// within `tempoSettleSeconds`, nor at the host block before or behind it, is a
// step; changes that near to each other are a ramp.
inline constexpr double tempoStep = 0.01;
inline constexpr double tempoSettleSeconds = 0.25;
// A position that tells nothing. `distrustJumps` jumps in a row, each less
// than `jumpRowSeconds` behind the one before or at the next host block, and
// the layer keeps time itself; the position is followed again once it has run
// for `returnSeconds` without a jump.
inline constexpr int distrustJumps = 3;
inline constexpr double jumpRowSeconds = 0.25;
inline constexpr double returnSeconds = 1.0;
// A gain this near its target has arrived.
inline constexpr double gainFloor = 1e-12;
} // namespace amanita::dsp::undertow
